### ISSUE TITLE
Incorrect number of bytes for basic report command?

### ISSUE THREAD

**Issue by youngmit** [Roba1993/rzw#15]
Looking at the [specs](https://www.silabs.com/documents/login/miscellaneous/SDS13781-Z-Wave-Application-Command-Class-Specification.pdf), it seems that the basic report should be either 3 bytes (command class, command, value) or 5 bytes (command class, command, current value, target value, duration), depending on the version implemented.

In the code it expects 6.
https://github.com/Roba1993/rzw/blob/a0b08c56aed0c10ce6c068f8b060e52b97d05681/src/cmds/basic.rs#L29

Is this a bug, or do I misunderstand?

Thanks!

**Comment by Roba1993** [comment]
Hi @youngmit 

this should be correct for the v1 of the protocoll - for v2 this of course wrong.
Here are where the the single bytes should mean:
0 --> Node ID
1 --> Message Length
2 --> Command Class
3 --> Command
4 --> Value

**Comment by Roba1993** [comment]
Hi @youngmit 

yes it was also a bug - I fixed it with the last commit.
I just deep dived into the code and I must say, in the last three years I learned a lot more about Rust...
Some parts of the code have a really bad style.

Because I anyway redevelop my Home automation right now, I will spent some time now, to update this crate to a Rust 2018 edition and fix some flaws in the design.

**Comment by youngmit** [comment]
Yeah, I noticed that there were some peculiar parts of the crate. Let me know if there's anything I can do to help out.

**Comment by Roba1993** [comment]
Yeah it's a mixture of 3-4 people committed code and tried to adopt it to their use-cases.

I'm analyzing right now the crate from the bottom to top.
You can help here, to identify the critical sections if you want - 4 eyes are better then 2.
Maybe we can also have a video session, to review it together.
